Repository neutrinoceros/inifix, pull requests merged in 2021-11, with the labels that each got.

#78 DOC: update documentation (typos, details)
  README.md
Labels: documentation

#80 BUG: fix a bug in str casting
  CHANGELOG.md
  README.md
  inifix/__init__.py
  inifix/iniconf.py
  setup.cfg
  tests/test_iniconf.py
Labels: bug

#73 ENH: expose name column length parameter to users in inifix-format
  README.md
  inifix/format.py
  tests/data/format-column-size-in.ini
  tests/data/format-column-size-out-10.ini
  tests/data/format-column-size-out-20.ini
  tests/data/format-column-size-out-50.ini
  tests/test_format.py
Labels: enhancement

#83 BUG: fix formatter behaviour
  CHANGELOG.md
  inifix/format.py
  tests/test_format.py
Labels: bug
